# Exported from Render on 2025-06-24T01:36:07Z
services:
- type: web
  name: annu
  runtime: python
  repo: https://github.com/ufssh/SAINI-TXT.git
  plan: free
  envVars:
      - key: PORT
        value: 8080  # Default port value, update if needed
  region: singapore
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  autoDeployTrigger: commit
version: "1"
